### ISSUE TITLE
Add a container health check

### ISSUE THREAD

**Issue by MarcoIeni** [rust-lang/bors#121]
From the AWS console, the Health status of the task is Unknown:

<img width="1211" alt="image" src="https://github.com/user-attachments/assets/73a59ef2-3c4c-40b7-aa88-f00ab6fa09cb">

<img width="368" alt="image" src="https://github.com/user-attachments/assets/34a71c72-96a9-4ca3-a756-c28cf59bb205">

I found the docs on how to add an health check [here](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_HealthCheck.html).

We could define an health check to tell AWS when the app is ready to accept requests. E.g. the health check can be an http endpoint, so that we start receiving requests after the http server started.

What do you think?

**Comment by Kobzol** [comment]
Yeah, that makes sense, should be easy to implement.

**Comment by MarcoIeni** [comment]
the aws dashboard still shows "unknown" so I need to investigate

**Comment by MarcoIeni** [comment]
https://github.com/rust-lang/simpleinfra/pull/559
I'll merge this tomorrow and check if it works in staging 👍

**Comment by Kobzol** [comment]
Thanks! Bors is an important service (well, this specific bors instance hopefully will be important one day :laughing:), so if we can get a health check that could perhaps even alert us in some way if it goes offline, that would be nice.

**Comment by MarcoIeni** [comment]
> this specific bors instance hopefully will be important one day 😆

It will 😁

This is now done. Closing this 🎉
