### ISSUE TITLE
Document how to write tests

### ISSUE THREAD

**Issue by MarcoIeni** [rust-lang/bors#175]
Write in `document.md` what are the necessary steps to run tests locally.

For sure it involves:

```shell
$ docker compose up -d
$ export DATABASE_URL=postgres://bors:bors@localhost:5432/bors
```

what else? Maybe some command to initialize the test db?

**Comment by Kobzol** [comment]
Some documentation on this is available [here](https://github.com/rust-lang/bors/blob/main/docs/development.md#database), although it does not explicitly state that it has to be done before running tests.
