### ISSUE TITLE
Enable logs in tests

### ISSUE THREAD

**Issue by MarcoIeni** [rust-lang/bors#177]
The logs are super useful. For example I was debugging #174 and by enabling logs I saw the following which is very useful:

![Image](https://github.com/user-attachments/assets/bda50946-8f6e-4b0e-8a03-e624ebdc2cfc)

It would be nice to enable logs for all tests by default.

I copy pasted the following to enable logs:

```
    tracing_subscriber::fmt()
        .with_env_filter(
            EnvFilter::builder()
                .with_default_directive(tracing::Level::INFO.into())
                .from_env()
                .expect("Cannot load RUST_LOG"),
        )
        .init();
```

What do you think?

**Comment by Kobzol** [comment]
We already depend on https://docs.rs/tracing-test/latest/tracing_test/. You can just slap `#[traced_test]` on top of a test to enable tracing log output in that test. I guess it would be nice to add this to the development documentation :)
