### ISSUE TITLE
Reload repository config while the bot is running

### ISSUE THREAD

**Issue by Kobzol** [rust-lang/bors#49]
The bot loads configuration from a `rust-bors.toml` file, located in the root of the repositories attached to the bot. Currently, it only reloads them when the bot itself is restarted.

It should be able to reload them without restarting itself. Either periodically (e.g. every 30 minutes or so), or it should react to pushes to the main branch on the repository, and reload the config after each push (or if it finds out that the `rust-bors.toml` file was modified).

**Comment by Mark-Simulacrum** [comment]
We should probably aim to match triagebot's behavior. I think that does a periodic refresh, but with a lower TTL (5 minutes?).

**Comment by Kobzol** [comment]
Yeah, it's probably for the best, as GH push webhooks can be lost.
