### ISSUE TITLE
Switch to `sqlx`

### ISSUE THREAD

**Issue by Kobzol** [rust-lang/bors#82]
I don't think that SeaORM is pulling its weight at the moment. Bors requires only a relatively simple database, and full ORM seems like an overkill to me. SeaORM requires us to have additional two crates in the workspace, juggle three different types per DB table, and it's not obvious to me what commands it executes and how it manages migrations.

For sake of transparency and easier understanding of what exactly we run against the DB, I would suggest to switch to `sqlx`.

**Comment by vohoanglong0107** [comment]
Do we need to migrate gradually from SeaORM to `sqlx`, or can we can just drop SeaORM and build `sqlx` models from scratch?

**Comment by Kobzol** [comment]
We don't need to do any incremental migration, we can just nuke the current DB, it's mostly empty anyway.

**Comment by Kobzol** [comment]
Fixed by https://github.com/rust-lang/bors/pull/87. Thanks!
