### ISSUE TITLE
Add a minimum CI run duration

### ISSUE THREAD

**Issue by Kobzol** [rust-lang/bors#84]
Sometimes, when [someone](https://github.com/rust-lang/rust/pull/124631) does a stupid thing and it completely removes all tests from CI, the CI workflows can finish very quickly, and e.g. run no jobs. Bors should have some configurable default to avoid accepting a merge when CI took less than a pre-defined time.

**Comment by MarcoIeni** [comment]
In case anyone wants to work on this, here's how you can add the field to the config: https://github.com/rust-lang/bors/compare/main...MarcoIeni:bors:min-ci
